server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 950828
    listener:
      simple:
        # 手动消费
        acknowledge-mode: manual
  relation-redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 4
  datasource:
    master:
      username: root
      password: 950828
      jdbc-url: jdbc:mysql://127.0.0.1:3306/persist_user_master?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: 950828
      url: jdbc:mysql://127.0.0.1:3306/persist_user_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
