server:
  port: 9091

spring:
  application:
    name: persist-eureka-server1

eureka:
  instance:
    hostname: persist.eureka.org1
    prefer-ip-address: false
  server:
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 300000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://persist.eureka.org2:9092/eureka
