server:
  port: 8888

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 950828
    # 确认消息已经发送到交换机
    publisher-confirms: true
    # 确认消息已经发送到队列
    publisher-returns: true
  relation-redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 4
